### ISSUE TITLE
Handle repository 404s on public pages

### ISSUE THREAD

**Issue by frankie567** [polarsource/polar#1066]
Example: https://polar.sh/polarsource/open-testing/issues/10

Related stack trace in Next.js:

```
ApiError: Not Found
    at catchErrorCodes (/var/task/clients/apps/web/.next/server/chunks/2904.js:420:15)
    at /var/task/clients/apps/web/.next/server/chunks/2904.js:450:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  url: 'https://api.polar.sh/api/v1/issues/lookup?external_url=https%3A%2F%2Fgithub.com%2Fpolarsource%2Fopen-testing%2Fissues%2F10',
  status: 404,
  statusText: 'Not Found',
  body: { detail: 'Issue by external_url not found' },
  request: {
    method: 'GET',
    url: '/api/v1/issues/lookup',
    query: {
      external_url: 'https://github.com/polarsource/open-testing/issues/10'
    },
    errors: { '422': 'Validation Error' }
  }
}
[Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] {
  digest: '2075855958'
}
ApiError: Not Found
    at catchErrorCodes (/var/task/clients/apps/web/.next/server/chunks/2904.js:420:15)
    at /var/task/clients/apps/web/.next/server/chunks/2904.js:450:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  url: 'https://api.polar.sh/api/v1/issues/lookup?external_url=https%3A%2F%2Fgithub.com%2Fpolarsource%2Fopen-testing%2Fissues%2F10',
  status: 404,
  statusText: 'Not Found',
  body: { detail: 'Issue by external_url not found' },
  request: {
    method: 'GET',
    url: '/api/v1/issues/lookup',
    query: {
      external_url: 'https://github.com/polarsource/open-testing/issues/10'
    },
    errors: { '422': 'Validation Error' }
  }
}
[Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] {
  digest: '2075855958'
}
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/polarsource) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog :^)

<a href="https://polar.sh/polarsource/polar/issues/1066">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/polarsource/polar/issues/1066/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/polarsource/polar/issues/1066/pledge.svg">
</picture>
</a>

**Comment by birkjernstrom** [comment]
I'll also create an issue to create a branded 404. The standard one is quite dull and I'm personally a big fan of offering a great experience even when s*(& hits the fan.
